# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b39978a80a4cf443f8d0c6a9a2f457a913858d84b73cbc16e81bd262a899644be7965c99e6d081f3001ebf300bd950a80bf8801ac271439e7a136b895e5ca30

test:
  secret_key_base: 1954341908838b0a77b17055a9c68896147f687fdfd47ebb24a0d039cc51e5c8e1b4906894c33dc0b83422fba633e19ca4affe8e424e2a6768ee261b6083e716

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f89fc348a40c70a1d79ab7a21322cca1ab9c77f9c1210d54c538f39c629401cd796b939f08e7732142381925824d8295a44872fee299ab88f6c1dad49b62dad4
